# This is a basic workflow to help you get started with Actions

name: CI-Temp

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.date.outputs.date }}
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Set current date as env variable
        run: echo "::set-output name=NOW::$(date +'%Y-%m-%d')" >> $GITHUB_ENV

  job2:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: echo ${{needs.build.outputs.output1}}
    - name: Echo current date
      run: echo $NOW
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
    - run: echo ${{needs.build.outputs.output1}}
    - name: Echo current date
      run: echo $NOW
  job4:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: echo ${{needs.build.outputs.output1}}
    - name: Echo current date
      run: echo $NOW      
